version: '3.4'

volumes:
  pg_data: {}

services:
  db:
    image: postgres:11
    restart: on-failure
    environment:
      POSTGRES_DB: shortener
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
  app:
    build: .
    command: pipenv run python3 manage.py runserver 0.0.0.0:8888
    volumes:
        - .:/app
    ports:
      - "8888:8888"
    depends_on:
      - db
