# Generated by Django 3.0.5 on 2020-04-16 21:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('full_url', models.TextField(validators=[django.core.validators.URLValidator()])),
                ('short_url', models.URLField()),
            ],
        ),
    ]
