# Generated by Django 3.0.5 on 2020-04-17 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='access_counter',
            field=models.IntegerField(default=0),
        ),
    ]
